[workspace]
members = ["crates/*", "tests"]
resolver = "2"

[workspace.dependencies]
hdi = "0.1"
hdk = "0.0.162"
serde = "1"
holochain = "0.0.174"

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"
