---
environment_path: ".sandbox/2cjQj7f7QhBzYxHhzV07A"
use_dangerous_test_keystore: false
signing_service_uri: ~
encryption_service_uri: ~
decryption_service_uri: ~
dpki: ~
keystore_path: ".sandbox/2cjQj7f7QhBzYxHhzV07A/keystore"
passphrase_service: ~
admin_interfaces:
  - driver:
      type: websocket
      port: 0
network: ~
