[package]
authors = ["guillem.cordoba@gmail.com"]
edition = "2018"
name = "hc_zome_profiles"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "hc_zome_profiles"

[dependencies]
derive_more = "0"
serde = "1"

hdk = "0.0.101-alpha.0"
holo_hash = "0.0.2-alpha.1"
